Improved name & version reporting
pop-os/support-panel pull request #4
Opened 2022-03-03 19:06 UTC by mmstick

Most systems have bogus info in `product_name` and `product_version`. Desktop motherboards populate only `board_name` and `board_version`. Our products put the same info for both. Should fix screenshots of systems showing the model and version as [ASUS System Product Name (Product Version](https://i.imgur.com/dxw7FOT.png)

2022-03-04 16:03 UTC, jacobgkau requested changes, later dismissed
On a System76 product, the model name and model number are flipped after this change.

Before:
![Screenshot from 2022-03-04 09-00-58](https://user-images.githubusercontent.com/7199422/156797394-89b8e70d-ac1b-4fa3-bfc1-4770bbd8c101.png)

After:
![Screenshot from 2022-03-04 09-01-29](https://user-images.githubusercontent.com/7199422/156797414-6d2f29f5-3224-4ff0-a00b-d0cf7dba2585.png)

2022-03-04 19:19 UTC, jacobgkau commented
Model and Version info is identical before and after the change on System76 hardware and in VirtualBox. Also, the window is now sized slightly better when launching the widget with `pop-support gtk` (instead of the minimum size, it's now a portrait window with minimum width but a larger height.) Going to have the team check one more piece of hardware before approving.

2022-04-18 15:46 UTC, jackpot51 approved these changes, later dismissed

2022-04-19 15:31 UTC, jackpot51 approved these changes

2022-04-19 17:13 UTC, leviport approved these changes

2022-04-19 17:18 UTC, merged